### ISSUE TITLE
[User Story 12] Blade's health bar

### ISSUE THREAD

**Issue by phgthanhng** [liu-benny/GameProg2-Project#70]
## Description
As a player, I can destroy the blades by pushing metallic objects 3 times to the blades

| Risk   | Priority | Story Points | Ideal Hours |
|--------|----------|--------------|-------------|
| Medium | High        | 3            | 6          |

## Tasks
- [x] #72
- [x] #73
- [x] #95

**Comment by gracexia02** [comment]
finish all the tasks
